### ISSUE TITLE
pcaPlot bug

### ISSUE THREAD

**Issue by kamalfartiyal84** [crukci-bioinformatics/qPLEXanalyzer#11]
pcaPlot(MSnset_Pnorm, labelColumn="Run", pointsize=1, x.nudge=5.3,omitIgG=TRUE,transform=FALSE)

x.nudge does now work when transform=FALSE

**Comment by AshKernow** [comment]
I am not able to replicate this. As far as I can tell x.nudge works fine with transform. Can you provide me with a more complete example of how you got this problem, with data.

**Comment by kamalfartiyal84** [comment]
Using the example given in the qPLEXanalyzer man page, the label does not move as intended irrespective of the value of x.nudge when transform=FALSE. It works fine when transform=TRUE :

pcaPlot(MSnSet_data, omitIgG = TRUE, labelColumn = "BioRep", x.nudge=3, transform=TRUE)
pcaPlot(MSnSet_data, omitIgG = TRUE, labelColumn = "BioRep", x.nudge=3, transform=FALSE)

**Comment by AshKernow** [comment]
Is this just because the axis is changing then transform is off? You may just need to increase the value.
If that's not it, please attach an RData file with the MSnSet_data object in it and I'll have a look.

**Comment by kamalfartiyal84** [comment]
There is no bug here. Its just when you have non-transformed values the scale of axis becomes large and you need to set very large value of x.nudge to see the effect. Closing the issue.
