### ISSUE TITLE
Updates in convertToMSnset to create Protein dataset

### ISSUE THREAD

**Issue by kamalfartiyal84** [crukci-bioinformatics/qPLEXanalyzer#7]
Changes in convertToMSnset to create Protein dataset as at present it supports only peptide dataset.
Sequences and Accessions column are mandatory for peptide dataset whereas only Accessions is mandatory for protein dataset. 

At present we use "peptide_" as prefix in defining featureNames for the peptide MSnSet using the following command:
featureNames(obj) <- paste0("peptide_",featureNames(obj))

However, if a protein dataset is generated we need to use Accessions to define featureNames for the protein MSnSet using the following command:
featureNames(obj) <- fData(obj)$Accessions

**Comment by AshKernow** [comment]
Checked the changes and updated the docs
